---
title: "README"
author: "Julian Alba"
date: "7/10/2020"
output: md_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


It could be confusing to extracting the information from the UCI DAT Database, here it will be explained, inthe first file we find four text files and two carpets, in here there are:

README.txt

features_info.txt

features.txt

activity_names.txt

/train

/test

from features.txt we obtained the features names, and from activity_names, the names of each activity performed.

In both files, train and test there are similiar files, we are interested in the x, y and subject text files, in x files there are all the values geaged by the celphone wher its columns correspond to the features names.

In y files there are numbers of theactivities performed, so each number in the column match with one of the activities that appeard in activity_names.txt in the same order.

Finally, in subject files appears the number of the subject that performd theactivities, and at the same time it correspond to the value in x, so in that way is how all the files are related.

Thank you for your attention.